### ISSUE TITLE
Secret Bookshelf Door

### ISSUE THREAD

**Issue by tranj456** [allegheny-college-cmpsc-100-fall-2022/woodshop#2]
## Describe your proposed improvement below in `150` words or fewer.

I want to add a function that when you use the bookshelf python file, it creates a new room directory that you can access and place things in the directory. I want it to be able to remove the directory and memorize what's stored inside the directory when you pick the bookshelf back up.

### Why is this a worthy improvement? How will fellow citizens benefit?

Having an additional secret room for whatever secret activities the citizens wish to hide from the mayor is something we would all want in terms of privacy.

## In a Markdown list, detail the steps that you think you need to complete to implement this proposal.

* Create a use() function that creates a new directory wherever you are currently located.
* Allows storage of items that is saved to that directory and bookshelf so that you can pick up the bookshelf and move the entire directory somewhere else.

## What knowledge do you believe you are _missing_ in order to execute this improvement.

The creation of a new directory is easy, but I don't know how I would be able to attach the directory to the bookshelf so that it memorizes the objects inside of it, and to delete the directory when the bookshelf is picked back up. I might have two separate uses of the bookshelf to achieve this before picking it back up.

**Comment by dluman** [comment]
This is the wrong repository for filing these, @tranj456 -- make this issue on your copy when you have a chance.
