### ISSUE TITLE
[PROPOSAL] Eat at Table

### ISSUE THREAD

**Issue by ditzenberger01** [allegheny-college-cmpsc-100-fall-2022/woodshop#3]
## Describe your proposed improvement below in `150` words or fewer.

I want to take it so you can eat and drink at the table and pick between two types of drinks and either lunch or dinner.

### Why is this a worthy improvement? How will fellow citizens benefit?

If citizens are hungry, they have the choice to keep "sitting" at the table and have food brought to them. At the end they will know how many drinks and how many foods were sent to them.

## In a Markdown list, detail the steps that you think you need to complete to implement this proposal.

* function for eating and drinking
* list of foods and drinks
* import random 
* string prints

## What knowledge do you believe you are _missing_ in order to execute this improvement.

*I'm not sure yet

**Comment by dluman** [comment]
This is the wrong repository for filing these, @ditzenberger01  -- make this issue on your copy when you have a chance.
