### ISSUE TITLE
[PROPOSAL] Bonfire

### ISSUE THREAD

**Issue by InsomniaLad** [allegheny-college-cmpsc-100-fall-2022/woodshop#5]
## Describe your proposed improvement below in `150` words or fewer.

Create a bonfire that over time consumes the wood it was built from, and eventually destroys itself

### Why is this a worthy improvement? How will fellow citizens benefit?

Who doesn't love a community bonfire?

## In a Markdown list, detail the steps that you think you need to complete to implement this proposal.

* Make a new set of intructions for bonfire
* Include a function that destroys the bonfire over time
* Add a feature that delets the bonfire once it has finished burning

## What knowledge do you believe you are _missing_ in order to execute this improvement.

Stuff with time, and destroying an object once it has been created

**Comment by dluman** [comment]
This is the wrong repository for filing these, @InsomniaLad  -- make this issue on your copy when you have a chance.
