### ISSUE TITLE
[PROPOSAL] Add books to Bookshelf

### ISSUE THREAD

**Issue by Jaclynpqc** [allegheny-college-cmpsc-100-fall-2022/woodshop#6]
Adding Books to Bookshelf. So that if I go to Bookshelf, I can see a list of books I've added

### Why is this a worthy improvement? How will fellow citizens benefit?
Each citizen now can create some sort of a reading list

## In a Markdown list, detail the steps that you think you need to complete to implement this proposal.
+ Making file to add books 
+ create the add (import json and os)
+ create a tbr.list 

## What knowledge do you believe you are _missing_ in order to execute this improvement.
* create a tbr list

**Comment by dluman** [comment]
This is the wrong repository for filing these, @Jaclynpqc  -- make this issue on your copy when you have a chance.
