### ISSUE TITLE
LazyBoy Chair

### ISSUE THREAD

**Issue by gyamfi01** [allegheny-college-cmpsc-100-fall-2022/woodshop#7]
## Describe your proposed improvement below in `150` words or fewer.

I would like to make the chair a lazy-boy chair.
### Why is this a worthy improvement? How will fellow citizens benefit?

These types of chairs are very comfortable to relax on instead of just a regular old chair.

## In a Markdown list, detail the steps that you think you need to complete to implement this proposal.

* function to make the chair recline
* function to make the chair incline
* function to make the chair kick up on the bottom 

## What knowledge do you believe you are _missing_ in order to execute this improvement.

I am not too sure.

**Comment by dluman** [comment]
This is the wrong repository for filing these, @gyamfi01  -- make this issue on your copy when you have a chance.
